CREATE TABLE `MEMBER` (
	`ID`	varchar(100)	NOT NULL,
	`PW`	varchar(100)	NOT NULL,
	`NAME`	varchar(10)	NULL,
	`NICK`	varchar(200)	NULL,
	`TEL`	varchar(200)	NULL,
	`BIRTH`	date	NULL,
	`GENDER`	varchar(6)	NULL,
	`EMAIL`	varchar(100)	NULL,
	`ADDRESS`	varchar(150)	NULL,
	`POSTCODE`	varchar(100)	NULL,
	`ADDR_DETAIL`	varchar(100)	NULL,
	`ADDR_EXTRA`	varchar(100)	NULL
);

CREATE TABLE `PRD_IMG` (
	`PRD_NO`	varchar(50)	NOT NULL,
	`SELLER_CODE`	varchar(100)	NOT NULL,
	`PRD_CODE`	VARCHAR(100)	NOT NULL,
	`IMG_PATH`	varchar(100)	NULL
);

CREATE TABLE `PRD` (
	`PRD_NO`	varchar(50)	NOT NULL,
	`SELLER_CODE`	varchar(100)	NOT NULL,
	`PRD_CODE`	VARCHAR(100)	NOT NULL,
	`PRD_NM`	varchar(100)	NULL,
	`PRD_DT`	varchar(100)	NULL,
	`PRD_PRICE`	varchar(255)	NULL,
	`PRD_START`	date	NULL,
	`PRD_END`	date	NULL,
	`PRD_SIGN`	date	NULL
);

CREATE TABLE `PRD_ST` (
	`SERIAL_NO`	varchar(100)	NOT NULL,
	`PRD_NO`	varchar(50)	NOT NULL,
	`SELLER_CODE`	varchar(100)	NOT NULL,
	`PRD_CODE`	VARCHAR(100)	NOT NULL
);

CREATE TABLE `SELLER` (
	`SELLER_CODE`	varchar(100)	NOT NULL,
	`COM_NM`	varchar(50)	NOT NULL,
	`COM_ADDR`	VARCHAR(100)	NULL,
	`COM_TEL`	VARCHAR(100)	NULL
);

CREATE TABLE `ORDER` (
	`ORDER_NO`	varchar(50)	NOT NULL,
	`ID`	varchar(100)	NOT NULL,
	`PRD_NO`	varchar(50)	NOT NULL,
	`SELLER_CODE`	varchar(100)	NOT NULL,
	`PRD_CODE`	VARCHAR(100)	NOT NULL,
	`TOTAL_PRICE`	varchar(100)	NULL,
	`TAKER_NM`	varchar(100)	NULL,
	`TAKER_TEL`	varchar(100)	NULL,
	`TAKER_ADDR`	varchar(100)	NULL,
	`ORDER_COM_TEL`	varchar(100)	NULL,
	`ORDER_MEMO`	varchar(100)	NULL,
	`ORDER_STATUS`	varchar(2)	NULL,
	`PAY_DATE`	date	NULL,
	`PAY_CODE`	VARCHAR(100)	NULL
);

CREATE TABLE `ORDER_PRD` (
	`ORDER_NO`	varchar(50)	NOT NULL,
	`ID`	varchar(100)	NOT NULL,
	`PRD_NO`	varchar(50)	NOT NULL,
	`SELLER_CODE`	varchar(100)	NOT NULL,
	`PRD_CODE`	VARCHAR(100)	NOT NULL,
	`SERIAL_NO`	varchar(100)	NOT NULL,
	`PRD_NO2`	varchar(50)	NOT NULL,
	`SELLER_CODE2`	varchar(100)	NOT NULL,
	`PRD_CODE2`	VARCHAR(100)	NOT NULL
);

CREATE TABLE `BASKET` (
	`ID`	varchar(100)	NOT NULL,
	`PRD_NO`	varchar(50)	NOT NULL,
	`SELLER_CODE`	varchar(100)	NOT NULL,
	`PRD_CODE`	VARCHAR(100)	NOT NULL
);

CREATE TABLE `PRD_CATE` (
	`PRD_CODE`	VARCHAR(100)	NOT NULL,
	`PRD_TYPE`	VARCHAR(100)	NULL
);

CREATE TABLE `COLL` (
	`COLL_NO`	varchar(100)	NOT NULL,
	`ID`	varchar(100)	NOT NULL,
	`SERIAL_NO`	varchar(100)	NOT NULL,
	`PRD_NO`	varchar(50)	NOT NULL,
	`SELLER_CODE`	varchar(100)	NOT NULL,
	`PRD_CODE`	VARCHAR(100)	NOT NULL,
	`GIVER_NM`	varchar(100)	NULL,
	`GIVER_TEL`	date	NULL,
	`GIVER_ADDR`	varchar(50)	NULL,
	`COLL_COM_TEL`	varchar(100)	NULL,
	`COLL_MEMO`	VARCHAR(100)	NULL,
	`COLL_STATUS`	varchar(100)	NULL,
	`COLL_DATE`	DATE	NULL
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`ID`
);

ALTER TABLE `PRD_IMG` ADD CONSTRAINT `PK_PRD_IMG` PRIMARY KEY (
	`PRD_NO`,
	`SELLER_CODE`,
	`PRD_CODE`
);

ALTER TABLE `PRD` ADD CONSTRAINT `PK_PRD` PRIMARY KEY (
	`PRD_NO`,
	`SELLER_CODE`,
	`PRD_CODE`
);

ALTER TABLE `PRD_ST` ADD CONSTRAINT `PK_PRD_ST` PRIMARY KEY (
	`SERIAL_NO`,
	`PRD_NO`,
	`SELLER_CODE`,
	`PRD_CODE`
);

ALTER TABLE `SELLER` ADD CONSTRAINT `PK_SELLER` PRIMARY KEY (
	`SELLER_CODE`
);

ALTER TABLE `ORDER` ADD CONSTRAINT `PK_ORDER` PRIMARY KEY (
	`ORDER_NO`,
	`ID`,
	`PRD_NO`,
	`SELLER_CODE`,
	`PRD_CODE`
);

ALTER TABLE `ORDER_PRD` ADD CONSTRAINT `PK_ORDER_PRD` PRIMARY KEY (
	`ORDER_NO`,
	`ID`,
	`PRD_NO`,
	`SELLER_CODE`,
	`PRD_CODE`,
	`SERIAL_NO`,
	`PRD_NO2`,
	`SELLER_CODE2`,
	`PRD_CODE2`
);

ALTER TABLE `BASKET` ADD CONSTRAINT `PK_BASKET` PRIMARY KEY (
	`ID`,
	`PRD_NO`,
	`SELLER_CODE`,
	`PRD_CODE`
);

ALTER TABLE `PRD_CATE` ADD CONSTRAINT `PK_PRD_CATE` PRIMARY KEY (
	`PRD_CODE`
);

ALTER TABLE `COLL` ADD CONSTRAINT `PK_COLL` PRIMARY KEY (
	`COLL_NO`,
	`ID`,
	`SERIAL_NO`,
	`PRD_NO`,
	`SELLER_CODE`,
	`PRD_CODE`
);

ALTER TABLE `PRD_IMG` ADD CONSTRAINT `FK_PRD_TO_PRD_IMG_1` FOREIGN KEY (
	`PRD_NO`
)
REFERENCES `PRD` (
	`PRD_NO`
);

ALTER TABLE `PRD_IMG` ADD CONSTRAINT `FK_PRD_TO_PRD_IMG_2` FOREIGN KEY (
	`SELLER_CODE`
)
REFERENCES `PRD` (
	`SELLER_CODE`
);

ALTER TABLE `PRD_IMG` ADD CONSTRAINT `FK_PRD_TO_PRD_IMG_3` FOREIGN KEY (
	`PRD_CODE`
)
REFERENCES `PRD` (
	`PRD_CODE`
);

ALTER TABLE `PRD` ADD CONSTRAINT `FK_SELLER_TO_PRD_1` FOREIGN KEY (
	`SELLER_CODE`
)
REFERENCES `SELLER` (
	`SELLER_CODE`
);

ALTER TABLE `PRD` ADD CONSTRAINT `FK_PRD_CATE_TO_PRD_1` FOREIGN KEY (
	`PRD_CODE`
)
REFERENCES `PRD_CATE` (
	`PRD_CODE`
);

ALTER TABLE `PRD_ST` ADD CONSTRAINT `FK_PRD_TO_PRD_ST_1` FOREIGN KEY (
	`PRD_NO`
)
REFERENCES `PRD` (
	`PRD_NO`
);

ALTER TABLE `PRD_ST` ADD CONSTRAINT `FK_PRD_TO_PRD_ST_2` FOREIGN KEY (
	`SELLER_CODE`
)
REFERENCES `PRD` (
	`SELLER_CODE`
);

ALTER TABLE `PRD_ST` ADD CONSTRAINT `FK_PRD_TO_PRD_ST_3` FOREIGN KEY (
	`PRD_CODE`
)
REFERENCES `PRD` (
	`PRD_CODE`
);

ALTER TABLE `ORDER` ADD CONSTRAINT `FK_MEMBER_TO_ORDER_1` FOREIGN KEY (
	`ID`
)
REFERENCES `MEMBER` (
	`ID`
);

ALTER TABLE `ORDER` ADD CONSTRAINT `FK_PRD_TO_ORDER_1` FOREIGN KEY (
	`PRD_NO`
)
REFERENCES `PRD` (
	`PRD_NO`
);

ALTER TABLE `ORDER` ADD CONSTRAINT `FK_PRD_TO_ORDER_2` FOREIGN KEY (
	`SELLER_CODE`
)
REFERENCES `PRD` (
	`SELLER_CODE`
);

ALTER TABLE `ORDER` ADD CONSTRAINT `FK_PRD_TO_ORDER_3` FOREIGN KEY (
	`PRD_CODE`
)
REFERENCES `PRD` (
	`PRD_CODE`
);

ALTER TABLE `ORDER_PRD` ADD CONSTRAINT `FK_ORDER_TO_ORDER_PRD_1` FOREIGN KEY (
	`ORDER_NO`
)
REFERENCES `ORDER` (
	`ORDER_NO`
);

ALTER TABLE `ORDER_PRD` ADD CONSTRAINT `FK_ORDER_TO_ORDER_PRD_2` FOREIGN KEY (
	`ID`
)
REFERENCES `ORDER` (
	`ID`
);

ALTER TABLE `ORDER_PRD` ADD CONSTRAINT `FK_ORDER_TO_ORDER_PRD_3` FOREIGN KEY (
	`PRD_NO`
)
REFERENCES `ORDER` (
	`PRD_NO`
);

ALTER TABLE `ORDER_PRD` ADD CONSTRAINT `FK_ORDER_TO_ORDER_PRD_4` FOREIGN KEY (
	`SELLER_CODE`
)
REFERENCES `ORDER` (
	`SELLER_CODE`
);

ALTER TABLE `ORDER_PRD` ADD CONSTRAINT `FK_ORDER_TO_ORDER_PRD_5` FOREIGN KEY (
	`PRD_CODE`
)
REFERENCES `ORDER` (
	`PRD_CODE`
);

ALTER TABLE `ORDER_PRD` ADD CONSTRAINT `FK_PRD_ST_TO_ORDER_PRD_1` FOREIGN KEY (
	`SERIAL_NO`
)
REFERENCES `PRD_ST` (
	`SERIAL_NO`
);

ALTER TABLE `ORDER_PRD` ADD CONSTRAINT `FK_PRD_ST_TO_ORDER_PRD_2` FOREIGN KEY (
	`PRD_NO2`
)
REFERENCES `PRD_ST` (
	`PRD_NO`
);

ALTER TABLE `ORDER_PRD` ADD CONSTRAINT `FK_PRD_ST_TO_ORDER_PRD_3` FOREIGN KEY (
	`SELLER_CODE2`
)
REFERENCES `PRD_ST` (
	`SELLER_CODE`
);

ALTER TABLE `ORDER_PRD` ADD CONSTRAINT `FK_PRD_ST_TO_ORDER_PRD_4` FOREIGN KEY (
	`PRD_CODE2`
)
REFERENCES `PRD_ST` (
	`PRD_CODE`
);

ALTER TABLE `BASKET` ADD CONSTRAINT `FK_MEMBER_TO_BASKET_1` FOREIGN KEY (
	`ID`
)
REFERENCES `MEMBER` (
	`ID`
);

ALTER TABLE `BASKET` ADD CONSTRAINT `FK_PRD_TO_BASKET_1` FOREIGN KEY (
	`PRD_NO`
)
REFERENCES `PRD` (
	`PRD_NO`
);

ALTER TABLE `BASKET` ADD CONSTRAINT `FK_PRD_TO_BASKET_2` FOREIGN KEY (
	`SELLER_CODE`
)
REFERENCES `PRD` (
	`SELLER_CODE`
);

ALTER TABLE `BASKET` ADD CONSTRAINT `FK_PRD_TO_BASKET_3` FOREIGN KEY (
	`PRD_CODE`
)
REFERENCES `PRD` (
	`PRD_CODE`
);

ALTER TABLE `COLL` ADD CONSTRAINT `FK_MEMBER_TO_COLL_1` FOREIGN KEY (
	`ID`
)
REFERENCES `MEMBER` (
	`ID`
);

ALTER TABLE `COLL` ADD CONSTRAINT `FK_PRD_ST_TO_COLL_1` FOREIGN KEY (
	`SERIAL_NO`
)
REFERENCES `PRD_ST` (
	`SERIAL_NO`
);

ALTER TABLE `COLL` ADD CONSTRAINT `FK_PRD_ST_TO_COLL_2` FOREIGN KEY (
	`PRD_NO`
)
REFERENCES `PRD_ST` (
	`PRD_NO`
);

ALTER TABLE `COLL` ADD CONSTRAINT `FK_PRD_ST_TO_COLL_3` FOREIGN KEY (
	`SELLER_CODE`
)
REFERENCES `PRD_ST` (
	`SELLER_CODE`
);

ALTER TABLE `COLL` ADD CONSTRAINT `FK_PRD_ST_TO_COLL_4` FOREIGN KEY (
	`PRD_CODE`
)
REFERENCES `PRD_ST` (
	`PRD_CODE`
);

